#!/usr/bin/perl

$file1 = $ARGV[0];
$file2 = $ARGV[1];

#print "$ARGV[0] $ARGV[1] $ARGV[2]";

$out1 = "tmp1";
$out2 = "tmp2";

#print $out1;
#print $out2;

open(IN, $file1);
open(OUT, ">$out1");
while (<IN>)
{
   @pieces = split(/#/, $_);    #get stuff before the #
   $pieces[0] =~s/\s+$//;       #remove trailing whitespace
   print OUT "$pieces[0]\n";
}
close(IN);
close(OUT);
   
open(IN, $file2);
open(OUT, ">$out2");
while (<IN>)
{
   @pieces = split(/#/, $_);
   $pieces[0] =~s/\s+$//;  
   print OUT "$pieces[0]\n";
}
close(IN);
close(OUT);

system "/usr/bin/diff -b $out1 $out2";
#system "rm -f $out1 $out2";



